spring:
  application:
    name: literacy-platform-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/literacy_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:2005}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    flyway:
      enabled: true
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: ${SERVER_PORT:8080}

app:
  security:
    jwt-secret: ${JWT_SECRET:01234567890123456789012345678901}
    access-token-minutes: 15
    refresh-token-days: 7
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs
