create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    name varchar(120) not null,
    email varchar(180) not null unique,
    password_hash varchar(200) not null,
    role varchar(20) not null,
    audio_enabled boolean not null default true
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    user_id bigint not null references users(id) on delete cascade,
    token_hash varchar(128) not null unique,
    expires_at timestamp with time zone not null
);

create table units (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    title varchar(120) not null,
    description varchar(500) not null,
    sort_order integer not null,
    published boolean not null default false
);

create table lessons (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    unit_id bigint not null references units(id) on delete cascade,
    title varchar(120) not null,
    description varchar(500) not null,
    lesson_type varchar(30) not null,
    difficulty varchar(20) not null,
    base_xp integer not null,
    sort_order integer not null,
    published boolean not null default false
);

create table exercises (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    lesson_id bigint not null references lessons(id) on delete cascade,
    exercise_type varchar(30) not null,
    prompt varchar(500) not null,
    correct_answer varchar(255) not null,
    display_order integer not null
);

create table children (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    parent_id bigint not null references users(id) on delete cascade,
    name varchar(120) not null,
    age integer not null,
    avatar varchar(100) not null,
    starting_level integer not null,
    current_level integer not null,
    xp integer not null,
    daily_streak integer not null,
    progress_percent integer not null,
    last_lesson_completed_on date,
    last_active_at timestamp with time zone
);

create table lesson_completions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    child_id bigint not null references children(id) on delete cascade,
    lesson_id bigint not null references lessons(id) on delete cascade,
    accuracy double precision not null,
    duration_seconds bigint not null,
    stars integer not null,
    xp_earned integer not null,
    completed_at timestamp with time zone not null,
    unique (child_id, lesson_id)
);

create table badge_awards (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    child_id bigint not null references children(id) on delete cascade,
    code varchar(60) not null,
    title varchar(120) not null,
    description varchar(255) not null,
    awarded_at timestamp with time zone not null,
    unique (child_id, code)
);

create table notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    parent_id bigint not null references users(id) on delete cascade,
    child_id bigint references children(id) on delete set null,
    type varchar(30) not null,
    title varchar(150) not null,
    message varchar(500) not null,
    is_read boolean not null default false
);

create table admin_activity_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    admin_id bigint references users(id) on delete set null,
    action varchar(100) not null,
    entity_type varchar(100) not null,
    entity_id bigint not null,
    details varchar(500) not null
);

create index idx_children_parent on children(parent_id);
create index idx_lessons_unit on lessons(unit_id);
create index idx_exercises_lesson on exercises(lesson_id);
create index idx_completions_child on lesson_completions(child_id);
create index idx_notifications_parent on notifications(parent_id);
create index idx_admin_logs_created on admin_activity_logs(created_at desc);
