create table if not exists admin_activity_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    admin_id bigint references users(id) on delete set null,
    action varchar(100) not null,
    entity_type varchar(100) not null,
    entity_id bigint not null,
    details varchar(500) not null
);

create index if not exists idx_admin_logs_created on admin_activity_logs(created_at desc);
