create table if not exists exercise_submissions (
                                                    id bigint generated by default as identity primary key,
                                                    created_at timestamp with time zone not null,
                                                    updated_at timestamp with time zone not null,
                                                    child_id bigint not null references children(id) on delete cascade,
                                                    exercise_id bigint not null references exercises(id) on delete cascade,
                                                    submitted_answer varchar(500) not null,
                                                    correct boolean not null,
                                                    time_taken_seconds bigint not null,
                                                    submitted_at timestamp with time zone not null,
                                                    constraint uk_exercise_submission_child_exercise unique (child_id, exercise_id)
);

create index if not exists idx_exercise_submissions_child on exercise_submissions(child_id);
create index if not exists idx_exercise_submissions_exercise on exercise_submissions(exercise_id);
create index if not exists idx_lessons_published on lessons(published);
create index if not exists idx_lessons_difficulty on lessons(difficulty);
create index if not exists idx_lessons_type on lessons(lesson_type);
create index if not exists idx_badges_child on badge_awards(child_id);
